baseURL = "http://enricsoler.github.io/"
languageCode = "en-us"
title = "enricsoler.dev"
theme = "ananke"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/MaDDoGoS"
  instagram = ""
  youtube = ""
  github = "https://github.com/enricsoler"
  gitlab = ""
  linkedin = "https://es.linkedin.com/in/enricsolerrastrollo"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2